// D1 Baseball: 308 teams — Massey indices + NCAA IDs + StatBroadcast GIDs
// Updated: Feb 17, 2026

const TEAMS = [
  {name:"Abilene Christian",massey:"Abilene_Chr",abbr:"AC",slug:"abilene-christian",conf:"WAC",mi:1,gid:null,sid:614839},
  {name:"Air Force",massey:"Air_Force",abbr:"AF",slug:"air-force",conf:"MWC",mi:2,gid:null,sid:614845},
  {name:"Akron",massey:"Akron",abbr:"AKRO",slug:"akron",conf:"MAC",mi:3,gid:null,sid:614798},
  {name:"Alabama",massey:"Alabama",abbr:"BAMA",slug:"alabama",conf:"SEC",mi:4,gid:"alab",sid:614787},
  {name:"Alabama A&M",massey:"Alabama_A&M",abbr:"AA",slug:"alabama-am",conf:"SWAC",mi:5,gid:null,sid:614848},
  {name:"Alabama State",massey:"Alabama_St",abbr:"AS",slug:"alabama-state",conf:"SWAC",mi:6,gid:null,sid:614847},
  {name:"Alcorn",massey:"Alcorn_St",abbr:"ALCO",slug:"alcorn",conf:"SWAC",mi:7,gid:null,sid:614851},
  {name:"Appalachian State",massey:"Appalachian_St",abbr:"AS",slug:"appalachian-state",conf:"Sun Belt",mi:8,gid:null,sid:614852},
  {name:"Arizona",massey:"Arizona",abbr:"ARIZ",slug:"arizona",conf:"Big 12",mi:9,gid:"ariz",sid:614767},
  {name:"Arizona State",massey:"Arizona_St",abbr:"ASU",slug:"arizona-state",conf:"Big 12",mi:10,gid:"asu",sid:614853},
  {name:"Little Rock",massey:"Ark_Little_Rock",abbr:"LR",slug:"little-rock",conf:"OVC",mi:11,gid:null,sid:614840},
  {name:"Arkansas-Pine Bluff",massey:"Ark_Pine_Bluff",abbr:"APB",slug:"arkansas-pine-bluff",conf:"SWAC",mi:12,gid:null,sid:614854},
  {name:"Arkansas",massey:"Arkansas",abbr:"ARK",slug:"arkansas",conf:"SEC",mi:13,gid:"ark",sid:614834},
  {name:"Arkansas State",massey:"Arkansas_St",abbr:"AS",slug:"arkansas-state",conf:"Sun Belt",mi:14,gid:null,sid:614855},
  {name:"Army West Point",massey:"Army",abbr:"AWP",slug:"army-west-point",conf:"Patriot",mi:15,gid:null,sid:614763},
  {name:"Auburn",massey:"Auburn",abbr:"AUB",slug:"auburn",conf:"SEC",mi:16,gid:"aub",sid:614857},
  {name:"Austin Peay",massey:"Austin_Peay",abbr:"AP",slug:"austin-peay",conf:"ASUN",mi:17,gid:null,sid:614858},
  {name:"Ball State",massey:"Ball_St",abbr:"BS",slug:"ball-state",conf:"MAC",mi:18,gid:null,sid:614867},
  {name:"Baylor",massey:"Baylor",abbr:"BAY",slug:"baylor",conf:"Big 12",mi:19,gid:"bay",sid:614859},
  {name:"Bellarmine",massey:"Bellarmine",abbr:"BELL",slug:"bellarmine",conf:"ASUN",mi:20,gid:null,sid:614861},
  {name:"Belmont",massey:"Belmont",abbr:"BELM",slug:"belmont",conf:"MVC",mi:21,gid:null,sid:614754},
  {name:"Bethune-Cookman",massey:"Bethune-Cookman",abbr:"BC",slug:"bethune-cookman",conf:"SWAC",mi:22,gid:null,sid:614838},
  {name:"Binghamton",massey:"Binghamton",abbr:"BING",slug:"binghamton",conf:"AE",mi:23,gid:null,sid:614862},
  {name:"Boston College",massey:"Boston_College",abbr:"BC",slug:"boston-college",conf:"ACC",mi:24,gid:"bc",sid:614863},
  {name:"Bowling Green",massey:"Bowling_Green",abbr:"BG",slug:"bowling-green",conf:"MAC",mi:25,gid:null,sid:614864},
  {name:"Bradley",massey:"Bradley",abbr:"BRAD",slug:"bradley",conf:"MVC",mi:26,gid:null,sid:614865},
  {name:"Brown",massey:"Brown",abbr:"BROW",slug:"brown",conf:"Ivy",mi:27,gid:null,sid:614866},
  {name:"Bryant",massey:"Bryant",abbr:"BRYA",slug:"bryant",conf:"AE",mi:28,gid:null,sid:614868},
  {name:"Bucknell",massey:"Bucknell",abbr:"BUCK",slug:"bucknell",conf:"Patriot",mi:29,gid:null,sid:614869},
  {name:"Butler",massey:"Butler",abbr:"BUTL",slug:"butler",conf:"Big East",mi:30,gid:null,sid:614563},
  {name:"BYU",massey:"BYU",abbr:"BYU",slug:"byu",conf:"Big 12",mi:31,gid:"byu",sid:614564},
  {name:"Central Michigan",massey:"C_Michigan",abbr:"CM",slug:"central-michigan",conf:"MAC",mi:32,gid:null,sid:614581},
  {name:"California Baptist",massey:"Cal_Baptist",abbr:"CB",slug:"california-baptist",conf:"WAC",mi:33,gid:null,sid:614844},
  {name:"Cal Poly",massey:"Cal_Poly",abbr:"CP",slug:"cal-poly",conf:"Big West",mi:34,gid:null,sid:614566},
  {name:"California",massey:"California",abbr:"CAL",slug:"california",conf:"ACC",mi:35,gid:"cal",sid:614572},
  {name:"Campbell",massey:"Campbell",abbr:"CAMP",slug:"campbell",conf:"CAA",mi:36,gid:null,sid:614577},
  {name:"Canisius",massey:"Canisius",abbr:"CANI",slug:"canisius",conf:"MAAC",mi:37,gid:null,sid:614578},
  {name:"Central Arkansas",massey:"Cent_Arkansas",abbr:"CA",slug:"central-arkansas",conf:"ASUN",mi:38,gid:null,sid:614825},
  {name:"Central Connecticut State",massey:"Central_Conn",abbr:"CCS",slug:"central-connecticut-state",conf:"NEC",mi:39,gid:null,sid:614579},
  {name:"Charleston Southern",massey:"Charleston_So",abbr:"CS",slug:"charleston-southern",conf:"Big South",mi:40,gid:null,sid:614860},
  {name:"Charlotte",massey:"Charlotte",abbr:"CHAR",slug:"charlotte",conf:"AAC",mi:41,gid:null,sid:614676},
  {name:"Cincinnati",massey:"Cincinnati",abbr:"CIN",slug:"cincinnati",conf:"Big 12",mi:42,gid:"cin",sid:614582},
  {name:"The Citadel",massey:"Citadel",abbr:"TC",slug:"the-citadel",conf:"SoCon",mi:43,gid:null,sid:614574},
  {name:"Clemson",massey:"Clemson",abbr:"CLEM",slug:"clemson",conf:"ACC",mi:44,gid:"clem",sid:614584},
  {name:"Coastal Carolina",massey:"Coastal_Car",abbr:"CC",slug:"coastal-carolina",conf:"Sun Belt",mi:45,gid:null,sid:614585},
  {name:"College of Charleston",massey:"Col_Charleston",abbr:"COC",slug:"college-of-charleston",conf:"CAA",mi:46,gid:null,sid:614827},
  {name:"Columbia",massey:"Columbia",abbr:"COLU",slug:"columbia",conf:"Ivy",mi:47,gid:null,sid:614586},
  {name:"UConn",massey:"Connecticut",abbr:"UCONN",slug:"uconn",conf:"Big East",mi:48,gid:null,sid:614674},
  {name:"Coppin State",massey:"Coppin_St",abbr:"CS",slug:"coppin-state",conf:"NEC",mi:49,gid:null,sid:614588},
  {name:"Cornell",massey:"Cornell",abbr:"CORN",slug:"cornell",conf:"Ivy",mi:50,gid:null,sid:614589},
  {name:"Creighton",massey:"Creighton",abbr:"CREI",slug:"creighton",conf:"Big East",mi:51,gid:null,sid:614590},
  {name:"Cal State Bakersfield",massey:"CS_Bakersfield",abbr:"CSB",slug:"cal-state-bakersfield",conf:"Big West",mi:52,gid:null,sid:614569},
  {name:"Cal State Fullerton",massey:"CS_Fullerton",abbr:"CSF",slug:"cal-state-fullerton",conf:"Big West",mi:53,gid:null,sid:614565},
  {name:"Cal State Northridge",massey:"CS_Northridge",abbr:"CSN",slug:"cal-state-northridge",conf:"Big West",mi:54,gid:null,sid:614567},
  {name:"Sacramento State",massey:"CS_Sacramento",abbr:"SS",slug:"sacramento-state",conf:"WAC",mi:55,gid:null,sid:614726},
  {name:"Dallas Baptist",massey:"Dallas_Bap",abbr:"DB",slug:"dallas-baptist",conf:"C-USA",mi:56,gid:null,sid:614764},
  {name:"Dartmouth",massey:"Dartmouth",abbr:"DART",slug:"dartmouth",conf:"Ivy",mi:57,gid:null,sid:614591},
  {name:"Davidson",massey:"Davidson",abbr:"DAVI",slug:"davidson",conf:"A-10",mi:58,gid:null,sid:614592},
  {name:"Dayton",massey:"Dayton",abbr:"DAYT",slug:"dayton",conf:"A-10",mi:59,gid:null,sid:614593},
  {name:"Delaware",massey:"Delaware",abbr:"DELA",slug:"delaware",conf:"CAA",mi:60,gid:null,sid:614595},
  {name:"Delaware State",massey:"Delaware_St",abbr:"DS",slug:"delaware-state",conf:"NEC",mi:61,gid:null,sid:614594},
  {name:"Duke",massey:"Duke",abbr:"DUKE",slug:"duke",conf:"ACC",mi:62,gid:"duke",sid:614769},
  {name:"Eastern Illinois",massey:"E_Illinois",abbr:"EI",slug:"eastern-illinois",conf:"OVC",mi:63,gid:null,sid:614596},
  {name:"Eastern Kentucky",massey:"E_Kentucky",abbr:"EK",slug:"eastern-kentucky",conf:"ASUN",mi:64,gid:null,sid:614598},
  {name:"Eastern Michigan",massey:"E_Michigan",abbr:"EM",slug:"eastern-michigan",conf:"MAC",mi:65,gid:null,sid:614599},
  {name:"East Carolina",massey:"East_Carolina",abbr:"EC",slug:"east-carolina",conf:"AAC",mi:66,gid:null,sid:614597},
  {name:"Elon",massey:"Elon",abbr:"ELON",slug:"elon",conf:"CAA",mi:67,gid:null,sid:614600},
  {name:"ETSU",massey:"ETSU",abbr:"ETSU",slug:"etsu",conf:"SoCon",mi:68,gid:null,sid:614828},
  {name:"Evansville",massey:"Evansville",abbr:"EVAN",slug:"evansville",conf:"MVC",mi:69,gid:null,sid:614770},
  {name:"FDU",massey:"F_Dickinson",abbr:"FDU",slug:"fdu",conf:"NEC",mi:70,gid:null,sid:614841},
  {name:"Fairfield",massey:"Fairfield",abbr:"FAIR",slug:"fairfield",conf:"MAAC",mi:71,gid:null,sid:614602},
  {name:"FGCU",massey:"FGCU",abbr:"FGCU",slug:"fgcu",conf:"ASUN",mi:72,gid:null,sid:614605},
  {name:"Florida Atlantic",massey:"FL_Atlantic",abbr:"FA",slug:"florida-atlantic",conf:"AAC",mi:73,gid:null,sid:614603},
  {name:"Florida",massey:"Florida",abbr:"UF",slug:"florida",conf:"SEC",mi:74,gid:"fla",sid:614604},
  {name:"Florida A&M",massey:"Florida_A&M",abbr:"FA",slug:"florida-am",conf:"SWAC",mi:75,gid:null,sid:614607},
  {name:"FIU",massey:"Florida_Intl",abbr:"FIU",slug:"fiu",conf:"C-USA",mi:76,gid:null,sid:614601},
  {name:"Florida State",massey:"Florida_St",abbr:"FSU",slug:"florida-state",conf:"ACC",mi:77,gid:"fsu",sid:614606},
  {name:"Fordham",massey:"Fordham",abbr:"FORD",slug:"fordham",conf:"A-10",mi:78,gid:null,sid:614608},
  {name:"Fresno State",massey:"Fresno_St",abbr:"FS",slug:"fresno-state",conf:"MWC",mi:79,gid:null,sid:614768},
  {name:"George Washington",massey:"G_Washington",abbr:"GW",slug:"george-washington",conf:"A-10",mi:80,gid:null,sid:614609},
  {name:"Georgia Southern",massey:"Ga_Southern",abbr:"GS",slug:"georgia-southern",conf:"Sun Belt",mi:81,gid:null,sid:614615},
  {name:"Gardner-Webb",massey:"Gardner_Webb",abbr:"GW",slug:"gardner-webb",conf:"Big South",mi:82,gid:null,sid:614612},
  {name:"George Mason",massey:"George_Mason",abbr:"GM",slug:"george-mason",conf:"A-10",mi:83,gid:null,sid:614829},
  {name:"Georgetown",massey:"Georgetown",abbr:"GEOR",slug:"georgetown",conf:"Big East",mi:84,gid:null,sid:614610},
  {name:"Georgia",massey:"Georgia",abbr:"UGA",slug:"georgia",conf:"SEC",mi:85,gid:"geo",sid:614611},
  {name:"Georgia State",massey:"Georgia_St",abbr:"GS",slug:"georgia-state",conf:"Sun Belt",mi:86,gid:null,sid:614613},
  {name:"Georgia Tech",massey:"Georgia_Tech",abbr:"GT",slug:"georgia-tech",conf:"ACC",mi:87,gid:"gatech",sid:614614},
  {name:"Gonzaga",massey:"Gonzaga",abbr:"GONZ",slug:"gonzaga",conf:"WCC",mi:88,gid:null,sid:614616},
  {name:"Grambling",massey:"Grambling",abbr:"GRAM",slug:"grambling",conf:"SWAC",mi:89,gid:null,sid:614771},
  {name:"Grand Canyon",massey:"Grand_Canyon",abbr:"GC",slug:"grand-canyon",conf:"WAC",mi:90,gid:null,sid:614830},
  {name:"Harvard",massey:"Harvard",abbr:"HARV",slug:"harvard",conf:"Ivy",mi:91,gid:null,sid:614617},
  {name:"Hawaii",massey:"Hawaii",abbr:"HAWA",slug:"hawaii",conf:"Big West",mi:92,gid:null,sid:614618},
  {name:"High Point",massey:"High_Point",abbr:"HP",slug:"high-point",conf:"Big South",mi:93,gid:null,sid:614766},
  {name:"Hofstra",massey:"Hofstra",abbr:"HOFS",slug:"hofstra",conf:"CAA",mi:94,gid:null,sid:614619},
  {name:"Holy Cross",massey:"Holy_Cross",abbr:"HC",slug:"holy-cross",conf:"Patriot",mi:95,gid:null,sid:614620},
  {name:"Houston",massey:"Houston",abbr:"HOU",slug:"houston",conf:"Big 12",mi:96,gid:"hou",sid:614622},
  {name:"Houston Christian",massey:"Houston_Chr",abbr:"HC",slug:"houston-christian",conf:"Southland",mi:97,gid:null,sid:614621},
  {name:"Illinois-Chicago",massey:"IL_Chicago",abbr:"IC",slug:"illinois-chicago",conf:"MVC",mi:98,gid:null,sid:614627},
  {name:"Illinois",massey:"Illinois",abbr:"ILL",slug:"illinois",conf:"Big Ten",mi:99,gid:"ill",sid:614624},
  {name:"Illinois State",massey:"Illinois_St",abbr:"IS",slug:"illinois-state",conf:"MVC",mi:100,gid:null,sid:614623},
  {name:"Incarnate Word",massey:"Incarnate_Word",abbr:"IW",slug:"incarnate-word",conf:"Southland",mi:101,gid:null,sid:614626},
  {name:"Indiana",massey:"Indiana",abbr:"IND",slug:"indiana",conf:"Big Ten",mi:102,gid:"iu",sid:614629},
  {name:"Indiana State",massey:"Indiana_St",abbr:"IS",slug:"indiana-state",conf:"MVC",mi:103,gid:null,sid:614630},
  {name:"Iona",massey:"Iona",abbr:"IONA",slug:"iona",conf:"MAAC",mi:104,gid:null,sid:614631},
  {name:"Iowa",massey:"Iowa",abbr:"IOWA",slug:"iowa",conf:"Big Ten",mi:105,gid:"iowa",sid:614633},
  {name:"Jackson State",massey:"Jackson_St",abbr:"JS",slug:"jackson-state",conf:"SWAC",mi:106,gid:null,sid:614632},
  {name:"Jacksonville",massey:"Jacksonville",abbr:"JACK",slug:"jacksonville",conf:"ASUN",mi:107,gid:null,sid:614634},
  {name:"Jacksonville State",massey:"Jacksonville_St",abbr:"JS",slug:"jacksonville-state",conf:"C-USA",mi:108,gid:null,sid:614636},
  {name:"James Madison",massey:"James_Madison",abbr:"JM",slug:"james-madison",conf:"Sun Belt",mi:109,gid:null,sid:614635},
  {name:"Kansas",massey:"Kansas",abbr:"KU",slug:"kansas",conf:"Big 12",mi:110,gid:"ku",sid:614831},
  {name:"Kansas State",massey:"Kansas_St",abbr:"KSU",slug:"kansas-state",conf:"Big 12",mi:111,gid:"kst",sid:614637},
  {name:"Kennesaw State",massey:"Kennesaw",abbr:"KS",slug:"kennesaw-state",conf:"C-USA",mi:112,gid:null,sid:614638},
  {name:"Kent State",massey:"Kent",abbr:"KS",slug:"kent-state",conf:"MAC",mi:113,gid:null,sid:null},
  {name:"Kentucky",massey:"Kentucky",abbr:"UK",slug:"kentucky",conf:"SEC",mi:114,gid:"kty",sid:614772},
  {name:"La Salle",massey:"La_Salle",abbr:"LS",slug:"la-salle",conf:"A-10",mi:115,gid:null,sid:614648},
  {name:"Lafayette",massey:"Lafayette",abbr:"LAFA",slug:"lafayette",conf:"Patriot",mi:116,gid:null,sid:614644},
  {name:"Lamar",massey:"Lamar",abbr:"LAMA",slug:"lamar",conf:"Southland",mi:117,gid:null,sid:614639},
  {name:"Le Moyne",massey:"Le_Moyne",abbr:"LM",slug:"le-moyne",conf:"NEC",mi:118,gid:null,sid:614640},
  {name:"Lehigh",massey:"Lehigh",abbr:"LEHI",slug:"lehigh",conf:"Patriot",mi:119,gid:null,sid:614760},
  {name:"Liberty",massey:"Liberty",abbr:"LIBE",slug:"liberty",conf:"C-USA",mi:120,gid:null,sid:614641},
  {name:"Lindenwood",massey:"Lindenwood",abbr:"LIND",slug:"lindenwood",conf:"OVC",mi:121,gid:null,sid:614642},
  {name:"Lipscomb",massey:"Lipscomb",abbr:"LIPS",slug:"lipscomb",conf:"ASUN",mi:122,gid:null,sid:614756},
  {name:"Long Island",massey:"LIU_Brooklyn",abbr:"LI",slug:"long-island",conf:"NEC",mi:123,gid:null,sid:614568},
  {name:"Long Beach State",massey:"Long_Beach_St",abbr:"LBS",slug:"long-beach-state",conf:"Big West",mi:124,gid:null,sid:614856},
  {name:"Longwood",massey:"Longwood",abbr:"LONG",slug:"longwood",conf:"Big South",mi:125,gid:null,sid:614643},
  {name:"Louisiana",massey:"Louisiana",abbr:"LOUI",slug:"louisiana",conf:"Sun Belt",mi:126,gid:null,sid:614748},
  {name:"Louisiana Tech",massey:"Louisiana_Tech",abbr:"LT",slug:"louisiana-tech",conf:"C-USA",mi:127,gid:null,sid:614646},
  {name:"Louisville",massey:"Louisville",abbr:"LOU",slug:"louisville",conf:"ACC",mi:128,gid:"lou",sid:614650},
  {name:"Loyola Marymount",massey:"Loy_Marymount",abbr:"LM",slug:"loyola-marymount",conf:"WCC",mi:129,gid:null,sid:614651},
  {name:"Louisiana State",massey:"LSU",abbr:"LS",slug:"louisiana-state",conf:"SEC",mi:130,gid:null,sid:614645},
  {name:"UMass Lowell",massey:"MA_Lowell",abbr:"UL",slug:"umass-lowell",conf:"AE",mi:131,gid:null,sid:614677},
  {name:"Maine",massey:"Maine",abbr:"MAIN",slug:"maine",conf:"AE",mi:132,gid:null,sid:614652},
  {name:"Manhattan",massey:"Manhattan",abbr:"MANH",slug:"manhattan",conf:"MAAC",mi:133,gid:null,sid:614654},
  {name:"Marist",massey:"Marist",abbr:"MARI",slug:"marist",conf:"MAAC",mi:134,gid:null,sid:614656},
  {name:"Marshall",massey:"Marshall",abbr:"MARS",slug:"marshall",conf:"Sun Belt",mi:135,gid:null,sid:614657},
  {name:"Maryland",massey:"Maryland",abbr:"MD",slug:"maryland",conf:"Big Ten",mi:136,gid:"umd",sid:614658},
  {name:"Massachusetts",massey:"Massachusetts",abbr:"MASS",slug:"massachusetts",conf:"A-10",mi:137,gid:null,sid:614826},
  {name:"McNeese",massey:"McNeese_St",abbr:"MCNE",slug:"mcneese",conf:"Southland",mi:138,gid:null,sid:614661},
  {name:"Maryland Eastern Shore",massey:"MD_E_Shore",abbr:"UMES",slug:"maryland-eastern-shore",conf:"NEC",mi:139,gid:null,sid:614850},
  {name:"Memphis",massey:"Memphis",abbr:"MEMP",slug:"memphis",conf:"AAC",mi:140,gid:null,sid:614660},
  {name:"Mercer",massey:"Mercer",abbr:"MERC",slug:"mercer",conf:"SoCon",mi:141,gid:null,sid:614663},
  {name:"Mercyhurst",massey:"Mercyhurst",abbr:"MERC",slug:"mercyhurst",conf:"NEC",mi:142,gid:null,sid:614662},
  {name:"Merrimack",massey:"Merrimack",abbr:"MERR",slug:"merrimack",conf:"MAAC",mi:143,gid:null,sid:614664},
  {name:"Miami (FL)",massey:"Miami_FL",abbr:"MIA",slug:"miami-fl",conf:"ACC",mi:144,gid:"miami",sid:614820},
  {name:"Miami (OH)",massey:"Miami_OH",abbr:"M(",slug:"miami-oh",conf:"MAC",mi:145,gid:null,sid:614665},
  {name:"Michigan",massey:"Michigan",abbr:"MICH",slug:"michigan",conf:"Big Ten",mi:146,gid:"um",sid:614666},
  {name:"Michigan State",massey:"Michigan_St",abbr:"MSU",slug:"michigan-state",conf:"Big Ten",mi:147,gid:"msu",sid:614667},
  {name:"Minnesota",massey:"Minnesota",abbr:"MINN",slug:"minnesota",conf:"Big Ten",mi:148,gid:"minn",sid:614670},
  {name:"Ole Miss",massey:"Mississippi",abbr:"MISS",slug:"ole-miss",conf:"SEC",mi:149,gid:"ole",sid:614777},
  {name:"Mississippi State",massey:"Mississippi_St",abbr:"MSST",slug:"mississippi-state",conf:"SEC",mi:150,gid:"msst",sid:614671},
  {name:"Missouri",massey:"Missouri",abbr:"MIZ",slug:"missouri",conf:"SEC",mi:151,gid:"miz",sid:614673},
  {name:"Missouri State",massey:"Missouri_St",abbr:"MS",slug:"missouri-state",conf:"MVC",mi:152,gid:null,sid:614688},
  {name:"Monmouth",massey:"Monmouth_NJ",abbr:"MONM",slug:"monmouth",conf:"CAA",mi:153,gid:null,sid:614689},
  {name:"Morehead State",massey:"Morehead_St",abbr:"MS",slug:"morehead-state",conf:"OVC",mi:154,gid:null,sid:614694},
  {name:"Mississippi Valley",massey:"MS_Valley_St",abbr:"MV",slug:"mississippi-valley",conf:"SWAC",mi:155,gid:null,sid:614672},
  {name:"Mount St. Mary\'s",massey:"Mt_St_Mary\'s",abbr:"MSM",slug:"mount-st-marys",conf:"MAAC",mi:156,gid:null,sid:614682},
  {name:"Middle Tennessee",massey:"MTSU",abbr:"MT",slug:"middle-tennessee",conf:"C-USA",mi:157,gid:null,sid:614669},
  {name:"Murray State",massey:"Murray_St",abbr:"MS",slug:"murray-state",conf:"MVC",mi:158,gid:null,sid:614799},
  {name:"Northern Colorado",massey:"N_Colorado",abbr:"NC",slug:"northern-colorado",conf:"Summit",mi:159,gid:null,sid:614701},
  {name:"North Dakota State",massey:"N_Dakota_St",abbr:"NDS",slug:"north-dakota-state",conf:"Summit",mi:160,gid:null,sid:614696},
  {name:"NIU",massey:"N_Illinois",abbr:"NIU",slug:"niu",conf:"MAC",mi:161,gid:null,sid:614690},
  {name:"Northern Kentucky",massey:"N_Kentucky",abbr:"NK",slug:"northern-kentucky",conf:"Horizon",mi:162,gid:null,sid:614700},
  {name:"Navy",massey:"Navy",abbr:"NAVY",slug:"navy",conf:"Patriot",mi:163,gid:null,sid:614773},
  {name:"North Carolina A&T",massey:"NC_A&T",abbr:"NCAT",slug:"nc-at",conf:"CAA",mi:164,gid:null,sid:614849},
  {name:"NC State",massey:"NC_State",abbr:"NCST",slug:"nc-state",conf:"ACC",mi:165,gid:"ncst",sid:614681},
  {name:"Omaha",massey:"NE_Omaha",abbr:"OMAH",slug:"omaha",conf:"Summit",mi:166,gid:null,sid:614708},
  {name:"Nebraska",massey:"Nebraska",abbr:"NEB",slug:"nebraska",conf:"Big Ten",mi:167,gid:"neb",sid:null},
  {name:"Nevada",massey:"Nevada",abbr:"NEVA",slug:"nevada",conf:"MWC",mi:168,gid:null,sid:614684},
  {name:"New Haven",massey:"New_Haven",abbr:"NH",slug:"new-haven",conf:"NEC",mi:169,gid:null,sid:614685},
  {name:"New Mexico",massey:"New_Mexico",abbr:"NM",slug:"new-mexico",conf:"MWC",mi:170,gid:null,sid:614686},
  {name:"New Mexico State",massey:"New_Mexico_St",abbr:"NMS",slug:"new-mexico-state",conf:"C-USA",mi:171,gid:null,sid:614774},
  {name:"New Orleans",massey:"New_Orleans",abbr:"NO",slug:"new-orleans",conf:"Southland",mi:172,gid:null,sid:614687},
  {name:"Niagara",massey:"Niagara",abbr:"NIAG",slug:"niagara",conf:"MAAC",mi:173,gid:null,sid:614843},
  {name:"Nicholls",massey:"Nicholls_St",abbr:"NICH",slug:"nicholls",conf:"Southland",mi:174,gid:null,sid:614675},
  {name:"NJIT",massey:"NJIT",abbr:"NJIT",slug:"njit",conf:"AE",mi:175,gid:null,sid:614835},
  {name:"Norfolk State",massey:"Norfolk_St",abbr:"NS",slug:"norfolk-state",conf:"NEC",mi:176,gid:null,sid:614692},
  {name:"North Alabama",massey:"North_Alabama",abbr:"NA",slug:"north-alabama",conf:"ASUN",mi:177,gid:null,sid:614693},
  {name:"North Carolina",massey:"North_Carolina",abbr:"UNC",slug:"north-carolina",conf:"ACC",mi:178,gid:"unc",sid:614695},
  {name:"North Florida",massey:"North_Florida",abbr:"NF",slug:"north-florida",conf:"ASUN",mi:179,gid:null,sid:614698},
  {name:"Northeastern",massey:"Northeastern",abbr:"NORT",slug:"northeastern",conf:"CAA",mi:180,gid:null,sid:614699},
  {name:"Northwestern",massey:"Northwestern",abbr:"NW",slug:"northwestern",conf:"Big Ten",mi:181,gid:"nw",sid:614702},
  {name:"Northwestern State",massey:"Northwestern_LA",abbr:"NS",slug:"northwestern-state",conf:"Southland",mi:182,gid:null,sid:614775},
  {name:"Notre Dame",massey:"Notre_Dame",abbr:"ND",slug:"notre-dame",conf:"ACC",mi:183,gid:"nd",sid:614703},
  {name:"Oakland",massey:"Oakland",abbr:"OAKL",slug:"oakland",conf:"Horizon",mi:184,gid:null,sid:614668},
  {name:"Ohio",massey:"Ohio",abbr:"OHIO",slug:"ohio",conf:"MAC",mi:185,gid:null,sid:614679},
  {name:"Ohio State",massey:"Ohio_St",abbr:"OSU",slug:"ohio-state",conf:"Big Ten",mi:186,gid:"osu",sid:614776},
  {name:"Oklahoma",massey:"Oklahoma",abbr:"OU",slug:"oklahoma",conf:"SEC",mi:187,gid:"ou",sid:614705},
  {name:"Oklahoma State",massey:"Oklahoma_St",abbr:"OKST",slug:"oklahoma-state",conf:"Big 12",mi:188,gid:"okst",sid:614704},
  {name:"Old Dominion",massey:"Old_Dominion",abbr:"OD",slug:"old-dominion",conf:"Sun Belt",mi:189,gid:null,sid:614706},
  {name:"Oral Roberts",massey:"Oral_Roberts",abbr:"OR",slug:"oral-roberts",conf:"Summit",mi:190,gid:null,sid:614709},
  {name:"Oregon",massey:"Oregon",abbr:"ORE",slug:"oregon",conf:"Big Ten",mi:191,gid:"oregon",sid:614710},
  {name:"Oregon State",massey:"Oregon_St",abbr:"ORST",slug:"oregon-state",conf:"Independent",mi:192,gid:"orst",sid:614711},
  {name:"Pacific",massey:"Pacific",abbr:"PACI",slug:"pacific",conf:"WCC",mi:193,gid:null,sid:614712},
  {name:"Penn",massey:"Penn",abbr:"PENN",slug:"penn",conf:"Ivy",mi:194,gid:null,sid:614832},
  {name:"Penn State",massey:"Penn_St",abbr:"PSU",slug:"penn-state",conf:"Big Ten",mi:195,gid:"psu",sid:614713},
  {name:"Pepperdine",massey:"Pepperdine",abbr:"PEPP",slug:"pepperdine",conf:"WCC",mi:196,gid:null,sid:614714},
  {name:"Pittsburgh",massey:"Pittsburgh",abbr:"PITT",slug:"pittsburgh",conf:"ACC",mi:197,gid:"pitt",sid:614757},
  {name:"Portland",massey:"Portland",abbr:"PORT",slug:"portland",conf:"WCC",mi:198,gid:null,sid:614715},
  {name:"Prairie View",massey:"Prairie_View",abbr:"PV",slug:"prairie-view",conf:"SWAC",mi:199,gid:null,sid:614716},
  {name:"Presbyterian",massey:"Presbyterian",abbr:"PRES",slug:"presbyterian",conf:"Big South",mi:200,gid:null,sid:614717},
  {name:"Princeton",massey:"Princeton",abbr:"PRIN",slug:"princeton",conf:"Ivy",mi:201,gid:null,sid:614718},
  {name:"Purdue",massey:"Purdue",abbr:"PUR",slug:"purdue",conf:"Big Ten",mi:202,gid:"pur",sid:614719},
  {name:"Queens (NC)",massey:"Queens_NC",abbr:"Q(",slug:"queens-nc",conf:"ASUN",mi:203,gid:null,sid:614720},
  {name:"Quinnipiac",massey:"Quinnipiac",abbr:"QUIN",slug:"quinnipiac",conf:"MAAC",mi:204,gid:null,sid:614721},
  {name:"Radford",massey:"Radford",abbr:"RADF",slug:"radford",conf:"Big South",mi:205,gid:null,sid:614750},
  {name:"Rhode Island",massey:"Rhode_Island",abbr:"RI",slug:"rhode-island",conf:"A-10",mi:206,gid:null,sid:614744},
  {name:"Rice",massey:"Rice",abbr:"RICE",slug:"rice",conf:"AAC",mi:207,gid:null,sid:614570},
  {name:"Richmond",massey:"Richmond",abbr:"RICH",slug:"richmond",conf:"A-10",mi:208,gid:null,sid:614722},
  {name:"Rider",massey:"Rider",abbr:"RIDE",slug:"rider",conf:"MAAC",mi:209,gid:null,sid:614724},
  {name:"Rutgers",massey:"Rutgers",abbr:"RUT",slug:"rutgers",conf:"Big Ten",mi:210,gid:"rug",sid:614725},
  {name:"South Dakota State",massey:"S_Dakota_St",abbr:"SDS",slug:"south-dakota-state",conf:"Summit",mi:211,gid:null,sid:614780},
  {name:"Southern Illinois",massey:"S_Illinois",abbr:"SI",slug:"southern-illinois",conf:"MVC",mi:212,gid:null,sid:614778},
  {name:"Sacred Heart",massey:"Sacred_Heart",abbr:"SH",slug:"sacred-heart",conf:"MAAC",mi:213,gid:null,sid:614727},
  {name:"Sam Houston",massey:"Sam_Houston_St",abbr:"SH",slug:"sam-houston",conf:"C-USA",mi:214,gid:null,sid:614732},
  {name:"Samford",massey:"Samford",abbr:"SAMF",slug:"samford",conf:"SoCon",mi:215,gid:null,sid:614733},
  {name:"San Diego",massey:"San_Diego",abbr:"SD",slug:"san-diego",conf:"WCC",mi:216,gid:null,sid:614734},
  {name:"San Diego State",massey:"San_Diego_St",abbr:"SDS",slug:"san-diego-state",conf:"MWC",mi:217,gid:null,sid:614833},
  {name:"San Francisco",massey:"San_Francisco",abbr:"SF",slug:"san-francisco",conf:"WCC",mi:218,gid:null,sid:614735},
  {name:"San Jose State",massey:"San_Jose_St",abbr:"SJS",slug:"san-jose-state",conf:"MWC",mi:219,gid:null,sid:614736},
  {name:"Santa Clara",massey:"Santa_Clara",abbr:"SC",slug:"santa-clara",conf:"WCC",mi:220,gid:null,sid:614737},
  {name:"USC Upstate",massey:"SC_Upstate",abbr:"UU",slug:"usc-upstate",conf:"Big South",mi:221,gid:null,sid:614753},
  {name:"Southeastern Louisiana",massey:"SE_Louisiana",abbr:"SL",slug:"southeastern-louisiana",conf:"Southland",mi:222,gid:null,sid:614723},
  {name:"SEMO",massey:"SE_Missouri_St",abbr:"SEMO",slug:"semo",conf:"OVC",mi:223,gid:null,sid:614739},
  {name:"Seattle U",massey:"Seattle",abbr:"SU",slug:"seattle-u",conf:"WAC",mi:224,gid:null,sid:614833},
  {name:"Seton Hall",massey:"Seton_Hall",abbr:"SH",slug:"seton-hall",conf:"Big East",mi:225,gid:null,sid:614740},
  {name:"SFA",massey:"SF_Austin",abbr:"SFA",slug:"sfa",conf:"Southland",mi:226,gid:null,sid:614779},
  {name:"Siena",massey:"Siena",abbr:"SIEN",slug:"siena",conf:"MAAC",mi:227,gid:null,sid:614741},
  {name:"SIUE",massey:"SIUE",abbr:"SIUE",slug:"siue",conf:"OVC",mi:228,gid:null,sid:614742},
  {name:"South Alabama",massey:"South_Alabama",abbr:"SA",slug:"south-alabama",conf:"Sun Belt",mi:229,gid:null,sid:614743},
  {name:"South Carolina",massey:"South_Carolina",abbr:"SCAR",slug:"south-carolina",conf:"SEC",mi:230,gid:"scar",sid:614758},
  {name:"South Florida",massey:"South_Florida",abbr:"SF",slug:"south-florida",conf:"AAC",mi:231,gid:null,sid:614745},
  {name:"Southern Indiana",massey:"Southern_Indiana",abbr:"SI",slug:"southern-indiana",conf:"OVC",mi:232,gid:null,sid:614785},
  {name:"Southern Mississippi",massey:"Southern_Miss",abbr:"SM",slug:"southern-mississippi",conf:"Sun Belt",mi:233,gid:null,sid:614749},
  {name:"Southern U",massey:"Southern_Univ",abbr:"SU",slug:"southern-u",conf:"SWAC",mi:234,gid:null,sid:614781},
  {name:"St. Bonaventure",massey:"St_Bonaventure",abbr:"SB",slug:"st-bonaventure",conf:"A-10",mi:235,gid:null,sid:614759},
  {name:"St. John\'s (NY)",massey:"St_John\'s",abbr:"SJ(",slug:"st-johns-ny",conf:"Big East",mi:236,gid:null,sid:614751},
  {name:"Saint Joseph\'s",massey:"St_Joseph\'s_PA",abbr:"SJ",slug:"saint-josephs",conf:"A-10",mi:237,gid:null,sid:614728},
  {name:"Saint Louis",massey:"St_Louis",abbr:"SL",slug:"saint-louis",conf:"A-10",mi:238,gid:null,sid:614729},
  {name:"Saint Mary\'s (CA)",massey:"St_Mary\'s_CA",abbr:"SM(",slug:"saint-marys-ca",conf:"WCC",mi:239,gid:null,sid:614731},
  {name:"Saint Peter\'s",massey:"St_Peter\'s",abbr:"SP",slug:"saint-peters",conf:"MAAC",mi:240,gid:null,sid:614730},
  {name:"St. Thomas (MN)",massey:"St_Thomas_MN",abbr:"ST(",slug:"st-thomas-mn",conf:"Summit",mi:241,gid:null,sid:614789},
  {name:"Stanford",massey:"Stanford",abbr:"STAN",slug:"stanford",conf:"ACC",mi:242,gid:"stan",sid:614761},
  {name:"Stetson",massey:"Stetson",abbr:"STET",slug:"stetson",conf:"ASUN",mi:243,gid:null,sid:614782},
  {name:"Stonehill",massey:"Stonehill",abbr:"STON",slug:"stonehill",conf:"NEC",mi:244,gid:null,sid:614752},
  {name:"Stony Brook",massey:"Stony_Brook",abbr:"SB",slug:"stony-brook",conf:"CAA",mi:245,gid:null,sid:614793},
  {name:"UAlbany",massey:"SUNY_Albany",abbr:"UALB",slug:"ualbany",conf:"AE",mi:246,gid:null,sid:614575},
  {name:"Texas A&M-Corpus Christi",massey:"TAM_C._Christi",abbr:"TACC",slug:"texas-am-corpus-christi",conf:"Southland",mi:247,gid:null,sid:614796},
  {name:"Tarleton St.",massey:"Tarleton_St",abbr:"TS",slug:"tarleton-st",conf:"WAC",mi:248,gid:null,sid:614788},
  {name:"TCU",massey:"TCU",abbr:"TCU",slug:"tcu",conf:"Big 12",mi:249,gid:"tcu",sid:614790},
  {name:"Tennessee",massey:"Tennessee",abbr:"TENN",slug:"tennessee",conf:"SEC",mi:250,gid:"tenn",sid:614747},
  {name:"Tennessee Tech",massey:"Tennessee_Tech",abbr:"TT",slug:"tennessee-tech",conf:"OVC",mi:251,gid:null,sid:614791},
  {name:"Texas",massey:"Texas",abbr:"TEX",slug:"texas",conf:"SEC",mi:252,gid:"tex",sid:614583},
  {name:"Texas A&M",massey:"Texas_A&M",abbr:"TAMU",slug:"texas-am",conf:"SEC",mi:253,gid:"tam",sid:614795},
  {name:"Texas State",massey:"Texas_St",abbr:"TS",slug:"texas-state",conf:"Sun Belt",mi:254,gid:null,sid:614850},
  {name:"Texas Tech",massey:"Texas_Tech",abbr:"TTU",slug:"texas-tech",conf:"Big 12",mi:255,gid:"ttu",sid:614573},
  {name:"UT Martin",massey:"TN_Martin",abbr:"UM",slug:"ut-martin",conf:"OVC",mi:256,gid:null,sid:614794},
  {name:"Toledo",massey:"Toledo",abbr:"TOLE",slug:"toledo",conf:"MAC",mi:257,gid:null,sid:614576},
  {name:"Towson",massey:"Towson",abbr:"TOWS",slug:"towson",conf:"CAA",mi:258,gid:null,sid:614755},
  {name:"Troy",massey:"Troy",abbr:"TROY",slug:"troy",conf:"Sun Belt",mi:259,gid:null,sid:614571},
  {name:"Tulane",massey:"Tulane",abbr:"TULA",slug:"tulane",conf:"AAC",mi:260,gid:null,sid:614580},
  {name:"Texas Southern",massey:"TX_Southern",abbr:"TS",slug:"texas-southern",conf:"SWAC",mi:261,gid:null,sid:614849},
  {name:"Alabama Birmingham",massey:"UAB",abbr:"AB",slug:"alabama-birmingham",conf:"AAC",mi:262,gid:null,sid:614846},
  {name:"UC Davis",massey:"UC_Davis",abbr:"UD",slug:"uc-davis",conf:"Big West",mi:263,gid:null,sid:614587},
  {name:"UC Irvine",massey:"UC_Irvine",abbr:"UI",slug:"uc-irvine",conf:"Big West",mi:264,gid:null,sid:614625},
  {name:"UC Riverside",massey:"UC_Riverside",abbr:"UR",slug:"uc-riverside",conf:"Big West",mi:265,gid:null,sid:614836},
  {name:"UC San Diego",massey:"UC_San_Diego",abbr:"USD",slug:"uc-san-diego",conf:"Big West",mi:266,gid:null,sid:614691},
  {name:"UC Santa Barbara",massey:"UC_Santa_Barbara",abbr:"USB",slug:"uc-santa-barbara",conf:"Big West",mi:267,gid:null,sid:614653},
  {name:"UCF",massey:"UCF",abbr:"UCF",slug:"ucf",conf:"Big 12",mi:268,gid:"ucf",sid:614655},
  {name:"UCLA",massey:"UCLA",abbr:"UCLA",slug:"ucla",conf:"Big Ten",mi:269,gid:"ucla",sid:614647},
  {name:"Louisiana-Monroe",massey:"ULM",abbr:"LM",slug:"louisiana-monroe",conf:"Sun Belt",mi:270,gid:null,sid:614649},
  {name:"Maryland Baltimore County",massey:"UMBC",abbr:"MBC",slug:"maryland-baltimore-county",conf:"AE",mi:271,gid:null,sid:614659},
  {name:"UNC Asheville",massey:"UNC_Asheville",abbr:"UA",slug:"unc-asheville",conf:"Big South",mi:272,gid:null,sid:614678},
  {name:"UNC Greensboro",massey:"UNC_Greensboro",abbr:"UG",slug:"unc-greensboro",conf:"SoCon",mi:273,gid:null,sid:614680},
  {name:"UNC Wilmington",massey:"UNC_Wilmington",abbr:"UW",slug:"unc-wilmington",conf:"CAA",mi:274,gid:null,sid:614837},
  {name:"Nevada Las Vegas",massey:"UNLV",abbr:"NLV",slug:"nevada-las-vegas",conf:"MWC",mi:275,gid:null,sid:614683},
  {name:"USC",massey:"USC",abbr:"USC",slug:"usc",conf:"Big Ten",mi:276,gid:"usc",sid:614792},
  {name:"UT Arlington",massey:"UT_Arlington",abbr:"UA",slug:"ut-arlington",conf:"WAC",mi:277,gid:null,sid:614707},
  {name:"Texas San Antonio",massey:"UT_San_Antonio",abbr:"TSA",slug:"texas-san-antonio",conf:"AAC",mi:278,gid:null,sid:614762},
  {name:"Utah",massey:"Utah",abbr:"UTAH",slug:"utah",conf:"Big 12",mi:279,gid:"utah",sid:614800},
  {name:"Utah Tech",massey:"Utah_Tech",abbr:"UT",slug:"utah-tech",conf:"WAC",mi:280,gid:null,sid:614786},
  {name:"Utah Valley",massey:"Utah_Valley",abbr:"UV",slug:"utah-valley",conf:"WAC",mi:281,gid:null,sid:614842},
  {name:"Texas Rio Grande Valley",massey:"UTRGV",abbr:"TRGV",slug:"texas-rio-grande-valley",conf:"Southland",mi:282,gid:null,sid:614797},
  {name:"Valparaiso",massey:"Valparaiso",abbr:"VALP",slug:"valparaiso",conf:"MVC",mi:283,gid:null,sid:614804},
  {name:"Vanderbilt",massey:"Vanderbilt",abbr:"VANDY",slug:"vanderbilt",conf:"SEC",mi:284,gid:"vand",sid:614805},
  {name:"VCU",massey:"VCU",abbr:"VCU",slug:"vcu",conf:"A-10",mi:285,gid:null,sid:614801},
  {name:"Villanova",massey:"Villanova",abbr:"VILL",slug:"villanova",conf:"Big East",mi:286,gid:null,sid:614802},
  {name:"Virginia",massey:"Virginia",abbr:"UVA",slug:"virginia",conf:"ACC",mi:287,gid:"va",sid:614803},
  {name:"Virginia Tech",massey:"Virginia_Tech",abbr:"VT",slug:"virginia-tech",conf:"ACC",mi:288,gid:"vt",sid:614807},
  {name:"VMI",massey:"VMI",abbr:"VMI",slug:"vmi",conf:"SoCon",mi:289,gid:null,sid:614806},
  {name:"Western Carolina",massey:"W_Carolina",abbr:"WC",slug:"western-carolina",conf:"SoCon",mi:290,gid:null,sid:614813},
  {name:"Western Illinois",massey:"W_Illinois",abbr:"WI",slug:"western-illinois",conf:"OVC",mi:291,gid:null,sid:614814},
  {name:"Western Michigan",massey:"W_Michigan",abbr:"WM",slug:"western-michigan",conf:"MAC",mi:292,gid:null,sid:614816},
  {name:"Wagner",massey:"Wagner",abbr:"WAGN",slug:"wagner",conf:"NEC",mi:293,gid:null,sid:614808},
  {name:"Wake Forest",massey:"Wake_Forest",abbr:"WAKE",slug:"wake-forest",conf:"ACC",mi:294,gid:"wake",sid:614809},
  {name:"Washington",massey:"Washington",abbr:"UW",slug:"washington",conf:"Big Ten",mi:295,gid:"wash",sid:614811},
  {name:"Washington State",massey:"Washington_St",abbr:"WS",slug:"washington-state",conf:"MWC",mi:296,gid:null,sid:614810},
  {name:"West Georgia",massey:"West_Georgia",abbr:"WG",slug:"west-georgia",conf:"ASUN",mi:297,gid:null,sid:614784},
  {name:"West Virginia",massey:"West_Virginia",abbr:"WVU",slug:"west-virginia",conf:"Big 12",mi:298,gid:"wvu",sid:614812},
  {name:"Milwaukee",massey:"WI_Milwaukee",abbr:"MILW",slug:"milwaukee",conf:"Horizon",mi:299,gid:null,sid:614746},
  {name:"Wichita State",massey:"Wichita_St",abbr:"WS",slug:"wichita-state",conf:"AAC",mi:300,gid:null,sid:614817},
  {name:"William & Mary",massey:"William_&_Mary",abbr:"W&M",slug:"william--mary",conf:"CAA",mi:301,gid:null,sid:614818},
  {name:"Winthrop",massey:"Winthrop",abbr:"WINT",slug:"winthrop",conf:"Big South",mi:302,gid:null,sid:614819},
  {name:"Western Kentucky",massey:"WKU",abbr:"WK",slug:"western-kentucky",conf:"C-USA",mi:303,gid:null,sid:614815},
  {name:"Wofford",massey:"Wofford",abbr:"WOFF",slug:"wofford",conf:"SoCon",mi:304,gid:null,sid:614765},
  {name:"Wright State",massey:"Wright_St",abbr:"WS",slug:"wright-state",conf:"Horizon",mi:305,gid:null,sid:614821},
  {name:"Xavier",massey:"Xavier",abbr:"XAVI",slug:"xavier",conf:"Big East",mi:306,gid:null,sid:614822},
  {name:"Yale",massey:"Yale",abbr:"YALE",slug:"yale",conf:"Ivy",mi:307,gid:null,sid:614823},
  {name:"Youngstown State",massey:"Youngstown_St",abbr:"YS",slug:"youngstown-state",conf:"Horizon",mi:308,gid:null,sid:614824},
];

const BY_GID={},BY_ABBR={},BY_NAME={},BY_MI={},BY_SID={};
for(const t of TEAMS){if(t.gid)BY_GID[t.gid]=t;BY_ABBR[t.abbr]=t;BY_NAME[t.name.toLowerCase()]=t;BY_MI[t.mi]=t;if(t.sid)BY_SID[t.sid]=t;}

function findTeam(n){if(!n)return null;const l=n.trim().toLowerCase();if(BY_NAME[l])return BY_NAME[l];const u=n.trim().toUpperCase();if(BY_ABBR[u])return BY_ABBR[u];for(const t of TEAMS){if(l.includes(t.name.toLowerCase())||t.name.toLowerCase().includes(l))return t;const m=t.massey.replace(/_/g," ").toLowerCase();if(l.includes(m)||m.includes(l))return t;}return null;}

module.exports={TEAMS,BY_GID,BY_ABBR,BY_NAME,BY_MI,BY_SID,findTeam};
